Update for Yocto kirkstone
This patch include two fixes.

ivi-id-agent: update dependencies to build on weston 7,8,10 :

Yocto kirkstone is using weston 10 and gcc 11.
The wayland-ivi-extension couldn't build on Yocto kirkstone based distribution.

1st patch referring libweston-desktop version is upgrade to fix configure error.

Fix build error in Yocto kirkstone :

Yocto kirkstone is using weston 10 and gcc 11.  The wayland-ivi-extension couldn't
build on Yocto kirkstone based distribution.

Essential error message:
  FAILED: ivi-layermanagement-api/ilmClient/libilmClient.so.2.2.0
  ivi-layermanagement-api/ilmClient/include/ilm_client_platform.h:38:
  multiple definition of `gIlmClientPlatformFunc';
  ivi-layermanagement-api/ilmClient/CMakeFiles/ilmClient.dir/src/ilm_client.c.o:
  /ivi-layermanagement-api/ilmClient/include/ilm_client_platform.h:38: first defined here
  collect2: error: ld returned 1 exit status

This error cased by variable definition in header file, it's included by some source files.

2nd patch that variable definition move into source file to fix this issue.

Signed-off-by: Naoto Yamaguchi <naoto.yamaguchi@aisin.co.jp>